# Generated by Django 2.2.1 on 2019-07-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridgenerate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_tags',
        ),
    ]
