# Generated by Django 2.2.1 on 2019-07-10 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridgenerate', '0002_remove_recipe_ingredient_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_tags',
            field=models.ManyToManyField(to='fridgenerate.Ingredient'),
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='fridge',
            name='ingredients',
            field=models.ManyToManyField(to='fridgenerate.Ingredient'),
        ),
        migrations.CreateModel(
            name='RecipeTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField(max_length=2000)),
                ('Recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='fridgenerate.Recipe')),
            ],
        ),
    ]
