# Generated by Django 2.2.1 on 2019-07-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridgenerate', '0003_auto_20190710_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipetest',
            old_name='Recipe',
            new_name='recipe',
        ),
    ]
